version: "3.8"

services:
  backend:
    build:
      context: ./Chat-bot-backend
    ports:
      - "8000:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./Chatbot-front
    ports:
      - "3000:3000"
    command: npm start
